on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 24.0
          elixir-version: 1.13.3
          experimental-otp: true
      - run: echo 'JAVA=SCRIPT\nER=LANG' > .env
      - run: mix deps.get
      - run: mix test