on: push
env:
  OTP_VERSION: 24.0
  ELIXIR_VERSION: 1.13.3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}
          experimental-otp: true
      - run: echo 'JAVA=SCRIPT\nER=LANG' > .env
      - run: mix deps.get
      - run: mix test

      - name: Elixir Hex, mix build Cache
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-${{ hashFiles('mix.lock') }}